test: fix flaky test
TestClusterLifecycle/cluster_init_and_basic_connectivity_test was
sometimes failing when run as follows:

```
go test -v -count=50 -run 'TestClusterLifecycle/cluster_init_and_basic_connectivity_test' ./go/test/endtoend
```

The error message is:
```
=== Configuring cell ===
⚙️  - Configuring cell: zone1
⚙️  - Using etcd at: localhost:11029
2025/09/30 13:05:15 ERROR Connection error, will keep retrying err="context deadline exceeded"
Error: cluster bootstrap failed: failed to setup cell zone1: failed to check cell 'zone1': Code: UNAVAILABLE
no connection available
```

Sometimes, when we're provisioning the cell, etcd doesn't seem to be
ready. So, the test fails. The code for checking etcd's health wasn't
doing anything, because etcd doesn't have a grpc_port or http_port in
its servicePorts. This change adds a working etcd health check.

Signed-off-by: Cuong Do <cuongdo@users.noreply.github.com>